# syntax = docker/dockerfile:1.2
FROM python:3.10

COPY . .
WORKDIR /

RUN --mount=type=secret,id=_env,dst=/.env

RUN pip install poetry==1.1.12
RUN poetry install

EXPOSE 80
CMD ["poetry", "run", "uvicorn", "app.main:app", "--port", "80"]
