# syntax = docker/dockerfile:1.2
FROM python:3.10

COPY . .
WORKDIR /

RUN --mount=type=secret,id=_env,dst=/.env

RUN pip install poetry==1.1.12
RUN poetry install

CMD poetry run uvicorn app.main:app --port 8000
EXPOSE 8000
